name = "Newquilt"
author = "comradeCrow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61b815a24b5b88a8700ff94385361bb569f18c8300b0c2ac39386d3bd5559566"

[versions]
minecraft = "1.20.1"
quilt = "0.22.0"
