name = "Newquilt"
author = "comradeCrow"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9416238b27de972a8b2204db275869356eec72f3194c0a572828512158d3c2df"

[versions]
minecraft = "1.20.1"
quilt = "0.22.0"
